const API="/api/v1";
const state={token:localStorage.getItem("pulsepath_token"),data:null,view:"dashboard",range:24};
const $=id=>document.getElementById(id); const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
async function request(path,opt={}){const headers={"Content-Type":"application/json",...(opt.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch(API+path,{...opt,headers});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.detail||"Request failed");return b}
function toast(msg){$("toast").textContent=msg;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2600)}
function metricMeta(key){return{heart_rate:["Heart rate","♥","bpm"],spo2:["Blood oxygen","◌","%"],temperature:["Temperature","◇","°C"],steps:["Activity","↗","steps"]}[key]}
function renderMetrics(){const m=state.data?.metrics||{};$("metric-grid").innerHTML=Object.entries(m).map(([k,v])=>{const [label,icon,unit]=metricMeta(k);return `<article class="metric"><div class="metric-top"><span class="label">${label}</span><span class="metric-icon">${icon}</span></div><div class="value">${v.latest_value??"—"} <span class="unit">${unit}</span></div><div class="trend">${v.count?`${v.count} readings · avg ${v.average} ${unit}`:"Waiting for wearable data"}</div></article>`}).join("")||`<div class="empty">Sign in to see your wearable metrics.</div>`}
function renderAlerts(){const a=state.data?.alerts||[];const html=a.length?a.slice(0,5).map(x=>`<div class="alert-row"><span class="alert-icon">!</span><div><strong>${esc(x.message)}</strong><small>${esc(x.metric)} · ${new Date(x.created_at).toLocaleString()}</small></div></div>`).join(""):`<div class="empty">No alerts — your dashboard is quiet.</div>`;$("alert-list").innerHTML=html;$("alerts-full").innerHTML=a.length?a.map(x=>`<div class="alert-row"><span class="alert-icon">!</span><div><strong>${esc(x.message)}</strong><small>${esc(x.severity)} · ${new Date(x.created_at).toLocaleString()} ${x.acknowledged?"· acknowledged":""}</small></div>${x.acknowledged?"":`<button class="text-button" onclick="ack(${x.id})">Acknowledge</button>`}</div>`).join(""):"<div class=\"empty\">No alerts yet.</div>";$("alert-count").textContent=a.filter(x=>!x.acknowledged).length}
async function ack(id){await request(`/alerts/${id}/acknowledge`,{method:"POST"});toast("Alert acknowledged");await loadDashboard()}
function renderDevices(){const d=state.data?.devices||[];$("device-grid").innerHTML=d.length?d.map(x=>`<article class="device-card"><div class="device-status">● ${x.active?"Connected":"Paused"}</div><h3>${esc(x.name)}</h3><p class="muted">${esc(x.model)} · Battery ${x.battery_percent}%</p><small class="muted">Last seen: ${x.last_seen_at?new Date(x.last_seen_at).toLocaleString():"Never"}</small><div class="device-token">Device ID ${x.id}<br>${esc(x.device_token)}</div></article>`).join(""): `<div class="empty">No wearable connected yet.<br>Click <b>Add device</b> to create a demo wearable.</div>`}
function renderVitals(){const m=state.data?.metrics||{};$("vitals-detail").innerHTML=Object.entries(m).map(([k,v])=>{const [label,,unit]=metricMeta(k);return `<article class="vital-large"><span class="eyebrow">${label.toUpperCase()}</span><div class="big-value">${v.latest_value??"—"} <small>${unit}</small></div><p class="muted">24h range: ${v.minimum??"—"} — ${v.maximum??"—"} · ${v.count} readings</p></article>`}).join("")||`<div class="empty">Sign in to view live vitals.</div>`}
function chart(points){if(!points.length){$("chart").innerHTML=`<div class="empty">No heart-rate readings yet. Use the simulator to generate data.</div>`;return}const w=760,h=230,p=18,vals=points.map(x=>x.value),min=Math.min(...vals)-2,max=Math.max(...vals)+2,xy=points.map((x,i)=>{const px=p+i*(w-2*p)/Math.max(1,points.length-1),py=h-p-(x.value-min)/(max-min)*(h-2*p);return `${px.toFixed(1)},${py.toFixed(1)}`}).join(" ");$("chart").innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#635bff" stop-opacity=".2"/><stop offset="1" stop-color="#635bff" stop-opacity="0"/></linearGradient></defs><polyline points="${p},${h-p} ${xy} ${w-p},${h-p}" fill="url(#g)" stroke="none"/><polyline points="${xy}" fill="none" stroke="#635bff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${points.slice(-1).map(x=>`<circle cx="${xy.split(" ").slice(-1)[0].split(",")[0]}" cy="${xy.split(" ").slice(-1)[0].split(",")[1]}" r="5" fill="#635bff"/>`).join("")}</svg>`}
async function loadChart(){if(!state.token){chart([]);return}try{chart(await request(`/health/timeseries/heart_rate?hours=${state.range}`))}catch(e){chart([])}}
async function loadDashboard(){if(!state.token){state.data=null;renderAll();return}try{state.data=await request("/dashboard");$("last-updated").textContent=`Updated ${new Date().toLocaleTimeString()}`;renderAll();await loadChart()}catch(e){toast(e.message)}}
function renderAll(){renderMetrics();renderAlerts();renderDevices();renderVitals();$("auth-button").textContent=state.token?"Account":"Sign in";$("logout").classList.toggle("hidden",!state.token)}
function show(view){state.view=view;document.querySelectorAll(".view").forEach(x=>x.classList.remove("active-view"));$(view).classList.add("active-view");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("page-title").textContent={dashboard:"Good evening",vitals:"Live vitals",devices:"Connected wearables",alerts:"Alerts & thresholds",assistant:"AI health assistant"}[view];if(view==="vitals")loadChart()}
async function authSubmit(e){e.preventDefault();const register=$("auth-title").dataset.mode==="register";try{const body=register?{email:$("auth-email").value,name:$("auth-name").value,password:$("auth-password").value}:{email:$("auth-email").value,password:$("auth-password").value};const r=await request(`/auth/${register?"register":"login"}`,{method:"POST",body:JSON.stringify(body)});state.token=r.access_token;localStorage.setItem("pulsepath_token",state.token);$("auth-dialog").close();toast(register?"Account created":"Welcome back");await loadDashboard()}catch(e){$("auth-error").textContent=e.message}}
$("auth-form").addEventListener("submit",authSubmit);$("auth-button").addEventListener("click",()=>state.token?show("dashboard"):$("auth-dialog").showModal());$("logout").addEventListener("click",()=>{localStorage.removeItem("pulsepath_token");state.token=null;toast("Signed out");show("dashboard");renderAll()});$("close-auth").addEventListener("click",()=>$("auth-dialog").close());$("toggle-auth").addEventListener("click",()=>{const reg=$("auth-title").dataset.mode!=="register";$("auth-title").dataset.mode=reg?"register":"login";$("auth-title").textContent=reg?"Create your account":"Welcome back";$("auth-submit").textContent=reg?"Create account":"Sign in";$("toggle-auth").textContent=reg?"Already registered? Sign in":"Create an account";$("name-field").classList.toggle("hidden",!reg);$("auth-password").autocomplete=reg?"new-password":"current-password"});document.querySelectorAll(".nav-item").forEach(x=>x.addEventListener("click",()=>show(x.dataset.view)));document.querySelectorAll("[data-view-link]").forEach(x=>x.addEventListener("click",()=>show(x.dataset.viewLink)));$("range-select").addEventListener("change",e=>{state.range=e.target.value;loadChart()});$("chat-form").addEventListener("submit",async e=>{e.preventDefault();if(!state.token)return $("auth-dialog").showModal();const input=$("chat-input"),msg=input.value.trim();if(!msg)return;const box=$("chat-messages");box.insertAdjacentHTML("beforeend",`<div class="message user"><b>You</b><span>${esc(msg)}</span></div>`);input.value="";try{const r=await request("/assistant/chat",{method:"POST",body:JSON.stringify({message:msg})});box.insertAdjacentHTML("beforeend",`<div class="message assistant"><b>PulsePath AI</b><span>${esc(r.answer)}</span></div>`);box.scrollTop=box.scrollHeight}catch(e){toast(e.message)}});$("add-device").addEventListener("click",async()=>{if(!state.token)return $("auth-dialog").showModal();const name=prompt("Wearable name","PulsePath Band");if(!name)return;try{await request("/devices",{method:"POST",body:JSON.stringify({name,model:"PulsePath Band"})});toast("Wearable connected");await loadDashboard();show("devices")}catch(e){toast(e.message)}});renderAll();loadDashboard();
